var searchData=
[
  ['aboutcomponent_0',['aboutcomponent',['../classAboutComponent.html#aba5dd2f2dab50c420b74b80a0cb9ef34',1,'AboutComponent::AboutComponent()'],['../classAboutComponent.html',1,'AboutComponent']]],
  ['aboutcomponent_2ecpp_1',['AboutComponent.cpp',['../AboutComponent_8cpp.html',1,'']]],
  ['aboutcomponent_2eh_2',['AboutComponent.h',['../AboutComponent_8h.html',1,'']]],
  ['adaptation_20inside_20alertwindow_3',['Layout adaptation inside AlertWindow',['../classUmsciZeroconfDiscoverComboComponent.html#autotoc_md39',1,'']]],
  ['added_4',['added',['../md_CHANGELOG.html#autotoc_md92',1,'Added'],['../md_CHANGELOG.html#autotoc_md140',1,'Added'],['../md_CHANGELOG.html#autotoc_md96',1,'Added'],['../md_CHANGELOG.html#autotoc_md100',1,'Added'],['../md_CHANGELOG.html#autotoc_md104',1,'Added'],['../md_CHANGELOG.html#autotoc_md108',1,'Added'],['../md_CHANGELOG.html#autotoc_md112',1,'Added'],['../md_CHANGELOG.html#autotoc_md116',1,'Added'],['../md_CHANGELOG.html#autotoc_md120',1,'Added'],['../md_CHANGELOG.html#autotoc_md124',1,'Added'],['../md_CHANGELOG.html#autotoc_md128',1,'Added'],['../md_CHANGELOG.html#autotoc_md132',1,'Added'],['../md_CHANGELOG.html#autotoc_md136',1,'Added']]],
  ['addr_5',['Addr',['../structDeviceController_1_1RemoteObject.html#a60a06af8d487a542104c6e81e629c01b',1,'DeviceController::RemoteObject']]],
  ['adjust_20the_20upmix_20indicator_6',['Step 4 — Set up and adjust the upmix indicator',['../index.html#autotoc_md52',1,'']]],
  ['alertwindow_7',['Layout adaptation inside AlertWindow',['../classUmsciZeroconfDiscoverComboComponent.html#autotoc_md39',1,'']]],
  ['align_20the_20ring_20to_20the_20room_8',['4b — Align the ring to the room',['../index.html#autotoc_md54',1,'']]],
  ['alignment_9',['Upmix monitoring and alignment',['../index.html#autotoc_md58',1,'']]],
  ['and_20adjust_20the_20upmix_20indicator_10',['Step 4 — Set up and adjust the upmix indicator',['../index.html#autotoc_md52',1,'']]],
  ['and_20alignment_11',['Upmix monitoring and alignment',['../index.html#autotoc_md58',1,'']]],
  ['and_20editing_12',['General soundobject position monitoring and editing',['../index.html#autotoc_md59',1,'']]],
  ['and_20embedded_20deployment_13',['Kiosk and embedded deployment',['../index.html#autotoc_md80',1,'']]],
  ['and_20first_20soundobject_14',['4a — Choose the channel format and first soundobject',['../index.html#autotoc_md53',1,'']]],
  ['and_20hittest_20dead_20zones_15',['Touch-zoom and hitTest dead zones',['../classUmsciSoundobjectsPaintComponent.html#autotoc_md29',1,'']]],
  ['and_20pan_16',['Zoom and pan',['../index.html#autotoc_md66',1,'']]],
  ['and_20pan_20internals_17',['Zoom and pan internals',['../index.html#autotoc_md85',1,'']]],
  ['and_20sibling_20synchronisation_18',['Viewport zoom and sibling synchronisation',['../classUmsciControlComponent.html#autotoc_md11',1,'']]],
  ['and_20touch_20routing_19',['hitTest and touch routing',['../classUmsciUpmixIndicatorPaintNControlComponent.html#autotoc_md34',1,'']]],
  ['and_20verify_20',['Step 2 — Connect and verify',['../index.html#autotoc_md48',1,'']]],
  ['anglestretch_21',['angleStretch',['../structUmsciSnapshotComponent_1_1UpmixSnapshot.html#a5073f91329d37e33ca24ceba7ce227cb',1,'UmsciSnapshotComponent::UpmixSnapshot']]],
  ['anotherinstancestarted_22',['anotherInstanceStarted',['../classMainApplication.html#abf43e959a633ba02a2bae4d9f058a900',1,'MainApplication']]],
  ['app_20functionality_23',['Umsci - app functionality',['../index.html#autotoc_md63',1,'']]],
  ['application_20architecture_20overview_24',['Application architecture overview',['../classMainComponent.html#autotoc_md3',1,'']]],
  ['applypalettestyle_25',['applyPaletteStyle',['../classMainApplication_1_1MainWindow.html#ab9716a08bda1af74eea932259dbf5b60',1,'MainApplication::MainWindow']]],
  ['applysettingsoption_26',['applySettingsOption',['../classMainComponent.html#a453a0ee11db0ab1baae366e976d79647',1,'MainComponent']]],
  ['architecture_27',['Code architecture',['../index.html#autotoc_md82',1,'']]],
  ['architecture_20overview_28',['Application architecture overview',['../classMainComponent.html#autotoc_md3',1,'']]],
  ['assignments_29',['Parameter assignments',['../index.html#autotoc_md78',1,'']]],
  ['attributeid_30',['AttributeID',['../classUmsciAppConfiguration.html#a5e67616c3aac0b239721e86c4837ad61',1,'UmsciAppConfiguration']]]
];
