Umsci: UmsciUpmixParamsComponent Class Reference
UmsciUpmixParamsComponent Class Reference
Floating left-side panel for batch-controlling Positioning_SourceSpread and Positioning_SourceDelayMode across all DS100 channels currently used by the upmix indicator.
#include <UmsciUpmixParamsComponent.h>
Public Types
enum class PanelState {
Tucked ,
Visible
}
Public Member Functions
UmsciUpmixParamsComponent ()
~UmsciUpmixParamsComponent () override
void setControlSize (int sizeLevel)
Sets size level 0=S (default), 1=M, 2=L. Triggers resized() + repaint().
int getPanelWidth () const
int getPanelHeight () const
int getGrabStripWidth () const
void setPanelState (PanelState state)
PanelState getPanelState () const
void setSpread (float spread)
Sets spread (0–1) without firing onSpreadChanged.
float getSpread () const
void setDelayMode (int mode)
Sets delay mode (0=Off, 1=Tight, 2=Full) without firing onDelayModeChanged.
int getDelayMode () const
void setSourceSpreadDeviceValue (std::int16_t sourceId, float spread)
Called when a Positioning_SourceSpread echo arrives for sourceId.
void setSourceDelayModeDeviceValue (std::int16_t sourceId, std::uint16_t mode)
Called when a Positioning_SourceDelayMode echo arrives for sourceId.
void setMonitoredSourceIds (const std::vector< std::int16_t > &ids)
Updates the set of DS100 channels to monitor for mismatch.
void clearDeviceValues ()
Clears stored device values and stops flashing. Call on disconnect.
void setHighlightColour (const juce::Colour &colour)
void paint (juce::Graphics &g) override
void paintOverChildren (juce::Graphics &g) override
void resized () override
void mouseUp (const juce::MouseEvent &e) override
void timerCallback () override
Public Attributes
std::function< void(PanelState)> onStateChangeRequested
Fired when the grab strip is clicked to request a state toggle.
std::function< void(float)> onSpreadChanged
Fired when the user changes the spread slider (value 0–1).
std::function< void(int)> onDelayModeChanged
Fired when the user clicks a delay mode button (0=Off, 1=Tight, 2=Full).
Static Public Attributes
static constexpr int s_panelMargin = 8
Detailed Description
Floating left-side panel for batch-controlling Positioning_SourceSpread and Positioning_SourceDelayMode across all DS100 channels currently used by the upmix indicator.
Sits directly above the snapshot panel on the left edge of the screen. When tucked, only the grab strip is visible. Slides in/out via onStateChangeRequested.
Controls
Spread slider (0–1): sets Positioning_SourceSpread on all monitored channels.
Delay mode radio (Off / Tight / Full): sets Positioning_SourceDelayMode (0 / 1 / 2) on all monitored channels.
Mismatch detection
The panel subscribes to per-source device feedback via setSourceSpreadDeviceValue() and setSourceDelayModeDeviceValue(). Whenever any monitored channel's device value differs from the aggregate control value, a sync_problem icon flashes over the panel (same pattern as UmsciDbprProjectComponent). Flashing stops once all channels match. Call clearDeviceValues() on disconnect to suppress spurious flashing before the next connection.
Definition at line 45 of file UmsciUpmixParamsComponent.h.
Member Enumeration Documentation
PanelState
enum class UmsciUpmixParamsComponent::PanelState strong
Panel visibility state — managed externally by MainComponent.
Enumerator
Tucked
Visible
Definition at line 49 of file UmsciUpmixParamsComponent.h.
Constructor & Destructor Documentation
UmsciUpmixParamsComponent()
UmsciUpmixParamsComponent::UmsciUpmixParamsComponent ()
Definition at line 21 of file UmsciUpmixParamsComponent.cpp.
References onDelayModeChanged, and onSpreadChanged.
~UmsciUpmixParamsComponent()
UmsciUpmixParamsComponent::~UmsciUpmixParamsComponent () override default
Member Function Documentation
clearDeviceValues()
void UmsciUpmixParamsComponent::clearDeviceValues ()
Clears stored device values and stops flashing. Call on disconnect.
Definition at line 191 of file UmsciUpmixParamsComponent.cpp.
getDelayMode()
int UmsciUpmixParamsComponent::getDelayMode () const
Definition at line 167 of file UmsciUpmixParamsComponent.cpp.
getGrabStripWidth()
int UmsciUpmixParamsComponent::getGrabStripWidth () const
Definition at line 105 of file UmsciUpmixParamsComponent.cpp.
Referenced by mouseUp(), paint(), paintOverChildren(), and resized().
getPanelHeight()
int UmsciUpmixParamsComponent::getPanelHeight () const
Definition at line 98 of file UmsciUpmixParamsComponent.cpp.
getPanelState()
UmsciUpmixParamsComponent::PanelState UmsciUpmixParamsComponent::getPanelState () const
Definition at line 144 of file UmsciUpmixParamsComponent.cpp.
getPanelWidth()
int UmsciUpmixParamsComponent::getPanelWidth () const
Definition at line 92 of file UmsciUpmixParamsComponent.cpp.
getSpread()
float UmsciUpmixParamsComponent::getSpread () const
Definition at line 157 of file UmsciUpmixParamsComponent.cpp.
mouseUp()
void UmsciUpmixParamsComponent::mouseUp (const juce::MouseEvent & e) override
Definition at line 333 of file UmsciUpmixParamsComponent.cpp.
References getGrabStripWidth(), onDelayModeChanged, onSpreadChanged, onStateChangeRequested, Tucked, and Visible.
paint()
void UmsciUpmixParamsComponent::paint (juce::Graphics & g) override
Definition at line 227 of file UmsciUpmixParamsComponent.cpp.
References getGrabStripWidth().
paintOverChildren()
void UmsciUpmixParamsComponent::paintOverChildren (juce::Graphics & g) override
Definition at line 247 of file UmsciUpmixParamsComponent.cpp.
References getGrabStripWidth().
resized()
void UmsciUpmixParamsComponent::resized () override
Definition at line 260 of file UmsciUpmixParamsComponent.cpp.
References getGrabStripWidth().
Referenced by setControlSize().
setControlSize()
void UmsciUpmixParamsComponent::setControlSize (int sizeLevel)
Sets size level 0=S (default), 1=M, 2=L. Triggers resized() + repaint().
Definition at line 85 of file UmsciUpmixParamsComponent.cpp.
References resized().
setDelayMode()
void UmsciUpmixParamsComponent::setDelayMode (int mode)
Sets delay mode (0=Off, 1=Tight, 2=Full) without firing onDelayModeChanged.
Definition at line 159 of file UmsciUpmixParamsComponent.cpp.
setHighlightColour()
void UmsciUpmixParamsComponent::setHighlightColour (const juce::Colour & colour)
Definition at line 204 of file UmsciUpmixParamsComponent.cpp.
setMonitoredSourceIds()
void UmsciUpmixParamsComponent::setMonitoredSourceIds (const std::vector< std::int16_t > & ids)
Updates the set of DS100 channels to monitor for mismatch.
Definition at line 183 of file UmsciUpmixParamsComponent.cpp.
setPanelState()
void UmsciUpmixParamsComponent::setPanelState (PanelState state)
Definition at line 143 of file UmsciUpmixParamsComponent.cpp.
setSourceDelayModeDeviceValue()
void UmsciUpmixParamsComponent::setSourceDelayModeDeviceValue (std::int16_t sourceId, std::uint16_t mode)
Called when a Positioning_SourceDelayMode echo arrives for sourceId.
Definition at line 177 of file UmsciUpmixParamsComponent.cpp.
setSourceSpreadDeviceValue()
void UmsciUpmixParamsComponent::setSourceSpreadDeviceValue (std::int16_t sourceId, float spread)
Called when a Positioning_SourceSpread echo arrives for sourceId.
Definition at line 171 of file UmsciUpmixParamsComponent.cpp.
setSpread()
void UmsciUpmixParamsComponent::setSpread (float spread)
Sets spread (0–1) without firing onSpreadChanged.
Definition at line 148 of file UmsciUpmixParamsComponent.cpp.
timerCallback()
void UmsciUpmixParamsComponent::timerCallback () override
Definition at line 355 of file UmsciUpmixParamsComponent.cpp.
Member Data Documentation
onDelayModeChanged
std::function<void(int)> UmsciUpmixParamsComponent::onDelayModeChanged
Fired when the user clicks a delay mode button (0=Off, 1=Tight, 2=Full).
Definition at line 103 of file UmsciUpmixParamsComponent.h.
Referenced by mouseUp(), and UmsciUpmixParamsComponent().
onSpreadChanged
std::function<void(float)> UmsciUpmixParamsComponent::onSpreadChanged
Fired when the user changes the spread slider (value 0–1).
Definition at line 101 of file UmsciUpmixParamsComponent.h.
Referenced by mouseUp(), and UmsciUpmixParamsComponent().
onStateChangeRequested
std::function<void(PanelState)> UmsciUpmixParamsComponent::onStateChangeRequested
Fired when the grab strip is clicked to request a state toggle.
Definition at line 99 of file UmsciUpmixParamsComponent.h.
Referenced by mouseUp().
s_panelMargin
constexpr int UmsciUpmixParamsComponent::s_panelMargin = 8 static constexpr
Left-edge margin from the window when the panel is fully visible (all sizes).
Definition at line 52 of file UmsciUpmixParamsComponent.h.
Referenced by MainComponent::resized().
The documentation for this class was generated from the following files:
Source/UmsciPaintNControlComponents/UmsciUpmixParamsComponent.h
Source/UmsciPaintNControlComponents/UmsciUpmixParamsComponent.cpp