Umsci: UmsciSnapshotComponent Class Reference
UmsciSnapshotComponent Class Reference
Floating side-panel for storing and recalling a single upmix transform snapshot.
#include <UmsciSnapshotComponent.h>
Classes
struct UpmixSnapshot
Public Types
enum class PanelState {
Tucked ,
Visible
}
Public Member Functions
void setControlSize (int sizeLevel)
Sets the panel size level: 0=S (default), 1=M, 2=L. Triggers resized() and repaint().
int getPanelWidth () const
Returns the current panel width for the active size level.
int getPanelHeight () const
Returns the current panel height for the active size level.
int getGrabStripWidth () const
Returns the current grab-strip width for the active size level.
UmsciSnapshotComponent ()
~UmsciSnapshotComponent () override
void paint (juce::Graphics &g) override
void resized () override
void mouseUp (const juce::MouseEvent &e) override
void setSnapshotData (const UpmixSnapshot &s)
Stores and displays the given snapshot values. Triggers a repaint.
void clearSnapshotData ()
Clears the stored snapshot and reverts to the empty state. Triggers a repaint.
void setHighlightColour (const juce::Colour &colour)
Sets the accent colour used for the panel border and buttons. Triggers a repaint.
void setRecallEnabled (bool enabled)
Enables or disables the recall button.
const std::optional< UpmixSnapshot > & getSnapshotData () const
Returns the currently stored snapshot, or std::nullopt if none has been stored.
void setPanelState (PanelState state)
Records the current state without animating the position. The parent calls this after starting the animation.
PanelState getPanelState () const
Returns the currently recorded panel state.
Public Attributes
std::function< void(PanelState newState)> onStateChangeRequested
Fired when the user clicks the grab strip and requests a state toggle.
std::function< void()> onStoreRequested
Fired when the user clicks the store button. The parent should capture the current upmix transform and call setSnapshotData().
std::function< void()> onRecallRequested
Fired when the user clicks the recall button. The parent should apply the stored snapshot to the control component.
Static Public Attributes
static constexpr int s_panelMargin = 8
Detailed Description
Floating side-panel for storing and recalling a single upmix transform snapshot.
Shares the same tucked/visible side-panel geometry as UmsciDbprProjectComponent. When tucked, only the rightmost grab strip is visible at the window's left edge. The panel sits directly above the dbpr project panel.
Parent responsibilities
The parent must:
Size this component to exactly (s_panelWidth × s_panelHeight).
Set the initial x-position: -(s_panelWidth - s_grabStripWidth) for Tucked, s_panelMargin for Visible.
Subscribe to onStateChangeRequested and animate the x-position when it fires.
Wire onStoreRequested / onRecallRequested to capture and apply the snapshot.
Call setHighlightColour() whenever the app's accent colour changes.
Definition at line 40 of file UmsciSnapshotComponent.h.
Member Enumeration Documentation
PanelState
enum class UmsciSnapshotComponent::PanelState strong
Panel visibility state. Managed externally by the parent component.
Enumerator
Tucked
Visible
Definition at line 44 of file UmsciSnapshotComponent.h.
Constructor & Destructor Documentation
UmsciSnapshotComponent()
UmsciSnapshotComponent::UmsciSnapshotComponent ()
Definition at line 21 of file UmsciSnapshotComponent.cpp.
References onRecallRequested, and onStoreRequested.
~UmsciSnapshotComponent()
UmsciSnapshotComponent::~UmsciSnapshotComponent () override default
Member Function Documentation
clearSnapshotData()
void UmsciSnapshotComponent::clearSnapshotData ()
Clears the stored snapshot and reverts to the empty state. Triggers a repaint.
Definition at line 241 of file UmsciSnapshotComponent.cpp.
getGrabStripWidth()
int UmsciSnapshotComponent::getGrabStripWidth () const
Returns the current grab-strip width for the active size level.
Definition at line 68 of file UmsciSnapshotComponent.cpp.
Referenced by mouseUp(), paint(), and resized().
getPanelHeight()
int UmsciSnapshotComponent::getPanelHeight () const
Returns the current panel height for the active size level.
Definition at line 61 of file UmsciSnapshotComponent.cpp.
getPanelState()
UmsciSnapshotComponent::PanelState UmsciSnapshotComponent::getPanelState () const
Returns the currently recorded panel state.
Definition at line 265 of file UmsciSnapshotComponent.cpp.
getPanelWidth()
int UmsciSnapshotComponent::getPanelWidth () const
Returns the current panel width for the active size level.
Definition at line 55 of file UmsciSnapshotComponent.cpp.
getSnapshotData()
const std::optional< UpmixSnapshot > & UmsciSnapshotComponent::getSnapshotData () const inline
Returns the currently stored snapshot, or std::nullopt if none has been stored.
Definition at line 121 of file UmsciSnapshotComponent.h.
mouseUp()
void UmsciSnapshotComponent::mouseUp (const juce::MouseEvent & e) override
Definition at line 212 of file UmsciSnapshotComponent.cpp.
References getGrabStripWidth(), onRecallRequested, onStateChangeRequested, onStoreRequested, Tucked, and Visible.
paint()
void UmsciSnapshotComponent::paint (juce::Graphics & g) override
Definition at line 118 of file UmsciSnapshotComponent.cpp.
References getGrabStripWidth().
resized()
void UmsciSnapshotComponent::resized () override
Definition at line 144 of file UmsciSnapshotComponent.cpp.
References getGrabStripWidth().
Referenced by setControlSize().
setControlSize()
void UmsciSnapshotComponent::setControlSize (int sizeLevel)
Sets the panel size level: 0=S (default), 1=M, 2=L. Triggers resized() and repaint().
Definition at line 48 of file UmsciSnapshotComponent.cpp.
References resized().
setHighlightColour()
void UmsciSnapshotComponent::setHighlightColour (const juce::Colour & colour)
Sets the accent colour used for the panel border and buttons. Triggers a repaint.
Definition at line 247 of file UmsciSnapshotComponent.cpp.
setPanelState()
void UmsciSnapshotComponent::setPanelState (PanelState state)
Records the current state without animating the position. The parent calls this after starting the animation.
Definition at line 260 of file UmsciSnapshotComponent.cpp.
setRecallEnabled()
void UmsciSnapshotComponent::setRecallEnabled (bool enabled)
Enables or disables the recall button.
Definition at line 254 of file UmsciSnapshotComponent.cpp.
setSnapshotData()
void UmsciSnapshotComponent::setSnapshotData (const UpmixSnapshot & s)
Stores and displays the given snapshot values. Triggers a repaint.
Definition at line 235 of file UmsciSnapshotComponent.cpp.
Member Data Documentation
onRecallRequested
std::function<void()> UmsciSnapshotComponent::onRecallRequested
Fired when the user clicks the recall button. The parent should apply the stored snapshot to the control component.
Definition at line 141 of file UmsciSnapshotComponent.h.
Referenced by mouseUp(), and UmsciSnapshotComponent().
onStateChangeRequested
std::function<void(PanelState newState)> UmsciSnapshotComponent::onStateChangeRequested
Fired when the user clicks the grab strip and requests a state toggle.
Definition at line 133 of file UmsciSnapshotComponent.h.
Referenced by mouseUp().
onStoreRequested
std::function<void()> UmsciSnapshotComponent::onStoreRequested
Fired when the user clicks the store button. The parent should capture the current upmix transform and call setSnapshotData().
Definition at line 137 of file UmsciSnapshotComponent.h.
Referenced by mouseUp(), and UmsciSnapshotComponent().
s_panelMargin
constexpr int UmsciSnapshotComponent::s_panelMargin = 8 static constexpr
Left-edge margin from the window when the panel is fully visible (all sizes).
Definition at line 48 of file UmsciSnapshotComponent.h.
Referenced by MainComponent::resized().
The documentation for this class was generated from the following files:
Source/UmsciPaintNControlComponents/UmsciSnapshotComponent.h
Source/UmsciPaintNControlComponents/UmsciSnapshotComponent.cpp