Umsci: UmsciDbprProjectComponent Class Reference
UmsciDbprProjectComponent Class Reference
Floating side-panel that shows a condensed summary of a loaded .dbpr project.
#include <UmsciDbprProjectComponent.h>
Public Types
enum class PanelState {
Tucked ,
Visible
}
Public Member Functions
void setControlSize (int sizeLevel)
Sets the panel size level: 0=S (default), 1=M, 2=L. Triggers resized() and repaint().
int getPanelWidth () const
Returns the current panel width for the active size level.
int getPanelHeight () const
Returns the current panel height for the active size level.
int getGrabStripWidth () const
Returns the current grab-strip width for the active size level.
UmsciDbprProjectComponent ()
~UmsciDbprProjectComponent () override
void paint (juce::Graphics &g) override
void resized () override
void mouseUp (const juce::MouseEvent &e) override
void setProjectData (const dbpr::ProjectData &data)
Replaces the displayed project summary. Triggers a repaint.
void clearProjectData ()
Clears the displayed project summary and reverts to the empty state. Triggers a repaint.
void setHighlightColour (const juce::Colour &colour)
Sets the accent colour used for the panel border and grab-strip indicator. Triggers a repaint.
void setMismatchFlashing (bool mismatch)
Starts or stops the cyclic mismatch-flash animation.
void setPanelState (PanelState state)
Records the current state without animating the position. The parent calls this after starting the animation.
PanelState getPanelState () const
Returns the currently recorded panel state.
Public Attributes
std::function< void(PanelState newState)> onStateChangeRequested
Fired when the user clicks the grab strip and requests a state toggle.
std::function< void()> onLoadRequested
Fired when the user clicks the load button. The parent should open a file chooser to select a .dbpr project file.
std::function< void()> onDeleteRequested
Fired when the user clicks the delete button. The parent should clear all project data and reset the app state.
std::function< void()> onSyncRequested
Placeholder – fired when the user clicks the sync button. Will be used in a future version to push project data to connected devices.
Static Public Attributes
static constexpr int s_panelMargin = 8
Detailed Description
Floating side-panel that shows a condensed summary of a loaded .dbpr project.
States
The panel has two states managed by the parent component (MainComponent):
State Description
Tucked Panel is pushed left off-screen. Only the rightmost grabStripWidth
pixels (the grab strip) remain visible at the window's left edge.
Visible Full panel is on-screen, left edge at panelMargin from the window left.
Parent responsibilities
The parent must:
Size this component to exactly (panelWidth × panelHeight).
Set the initial x-position: -(panelWidth - grabStripWidth) for Tucked, panelMargin for Visible.
Subscribe to onStateChangeRequested and animate/snap the component's x-position when the callback fires.
Call setHighlightColour() whenever the app's accent colour changes.
Grab-strip geometry (x = 0 is the panel's own left edge)
+-------- contentWidth --------+-- grabStripWidth --+
| DBPR Project                 |        |||          |
| 4 Coordinate Mappings        |        |||          |
| 52 Speakers                  |        |||          |
+------------------------------+--------------------+
When Tucked the parent positions the component so that only the grab strip is on-screen (at the window's left edge). Clicking anywhere in the grab strip fires onStateChangeRequested.
Definition at line 59 of file UmsciDbprProjectComponent.h.
Member Enumeration Documentation
PanelState
enum class UmsciDbprProjectComponent::PanelState strong
Panel visibility state. Managed externally by the parent component.
Enumerator
Tucked
Visible
Definition at line 63 of file UmsciDbprProjectComponent.h.
Constructor & Destructor Documentation
UmsciDbprProjectComponent()
UmsciDbprProjectComponent::UmsciDbprProjectComponent ()
Definition at line 21 of file UmsciDbprProjectComponent.cpp.
References onDeleteRequested, onLoadRequested, and onSyncRequested.
~UmsciDbprProjectComponent()
UmsciDbprProjectComponent::~UmsciDbprProjectComponent () override default
Member Function Documentation
clearProjectData()
void UmsciDbprProjectComponent::clearProjectData ()
Clears the displayed project summary and reverts to the empty state. Triggers a repaint.
Definition at line 311 of file UmsciDbprProjectComponent.cpp.
getGrabStripWidth()
int UmsciDbprProjectComponent::getGrabStripWidth () const
Returns the current grab-strip width for the active size level.
Definition at line 73 of file UmsciDbprProjectComponent.cpp.
Referenced by mouseUp(), paint(), and resized().
getPanelHeight()
int UmsciDbprProjectComponent::getPanelHeight () const
Returns the current panel height for the active size level.
Definition at line 66 of file UmsciDbprProjectComponent.cpp.
getPanelState()
UmsciDbprProjectComponent::PanelState UmsciDbprProjectComponent::getPanelState () const
Returns the currently recorded panel state.
Definition at line 348 of file UmsciDbprProjectComponent.cpp.
getPanelWidth()
int UmsciDbprProjectComponent::getPanelWidth () const
Returns the current panel width for the active size level.
Definition at line 60 of file UmsciDbprProjectComponent.cpp.
mouseUp()
void UmsciDbprProjectComponent::mouseUp (const juce::MouseEvent & e) override
Definition at line 272 of file UmsciDbprProjectComponent.cpp.
References getGrabStripWidth(), onDeleteRequested, onLoadRequested, onStateChangeRequested, onSyncRequested, Tucked, and Visible.
paint()
void UmsciDbprProjectComponent::paint (juce::Graphics & g) override
Definition at line 123 of file UmsciDbprProjectComponent.cpp.
References getGrabStripWidth().
resized()
void UmsciDbprProjectComponent::resized () override
Definition at line 150 of file UmsciDbprProjectComponent.cpp.
References getGrabStripWidth().
Referenced by setControlSize().
setControlSize()
void UmsciDbprProjectComponent::setControlSize (int sizeLevel)
Sets the panel size level: 0=S (default), 1=M, 2=L. Triggers resized() and repaint().
Definition at line 53 of file UmsciDbprProjectComponent.cpp.
References resized().
setHighlightColour()
void UmsciDbprProjectComponent::setHighlightColour (const juce::Colour & colour)
Sets the accent colour used for the panel border and grab-strip indicator. Triggers a repaint.
Definition at line 318 of file UmsciDbprProjectComponent.cpp.
setMismatchFlashing()
void UmsciDbprProjectComponent::setMismatchFlashing (bool mismatch)
Starts or stops the cyclic mismatch-flash animation.
When mismatch is true, the panel's highlight-coloured border and a sync-problem icon beside the title both flash at 500 ms intervals to indicate that the loaded dbpr data differs from the values reported by the connected device. Passing false stops the timer, hides the icon, and restores the solid border.
Definition at line 325 of file UmsciDbprProjectComponent.cpp.
setPanelState()
void UmsciDbprProjectComponent::setPanelState (PanelState state)
Records the current state without animating the position. The parent calls this after starting the animation.
Definition at line 343 of file UmsciDbprProjectComponent.cpp.
setProjectData()
void UmsciDbprProjectComponent::setProjectData (const dbpr::ProjectData & data)
Replaces the displayed project summary. Triggers a repaint.
Definition at line 304 of file UmsciDbprProjectComponent.cpp.
Member Data Documentation
onDeleteRequested
std::function<void()> UmsciDbprProjectComponent::onDeleteRequested
Fired when the user clicks the delete button. The parent should clear all project data and reset the app state.
Definition at line 136 of file UmsciDbprProjectComponent.h.
Referenced by mouseUp(), and UmsciDbprProjectComponent().
onLoadRequested
std::function<void()> UmsciDbprProjectComponent::onLoadRequested
Fired when the user clicks the load button. The parent should open a file chooser to select a .dbpr project file.
Definition at line 132 of file UmsciDbprProjectComponent.h.
Referenced by mouseUp(), and UmsciDbprProjectComponent().
onStateChangeRequested
std::function<void(PanelState newState)> UmsciDbprProjectComponent::onStateChangeRequested
Fired when the user clicks the grab strip and requests a state toggle.
The parent must respond by:
Calling setPanelState(newState) on this component.
Animating the component's x-position to -(panelWidth - grabStripWidth) (Tucked) or panelMargin (Visible).
Definition at line 128 of file UmsciDbprProjectComponent.h.
Referenced by mouseUp().
onSyncRequested
std::function<void()> UmsciDbprProjectComponent::onSyncRequested
Placeholder – fired when the user clicks the sync button. Will be used in a future version to push project data to connected devices.
Definition at line 140 of file UmsciDbprProjectComponent.h.
Referenced by mouseUp(), and UmsciDbprProjectComponent().
s_panelMargin
constexpr int UmsciDbprProjectComponent::s_panelMargin = 8 static constexpr
Left-edge margin from the window when the panel is fully visible (all sizes).
Definition at line 67 of file UmsciDbprProjectComponent.h.
Referenced by MainComponent::resized().
The documentation for this class was generated from the following files:
Source/UmsciPaintNControlComponents/UmsciDbprProjectComponent.h
Source/UmsciPaintNControlComponents/UmsciDbprProjectComponent.cpp