Umsci: UmsciAppConfiguration Class Reference
UmsciAppConfiguration Class Reference
Persists all Umsci user settings to an XML file via the JUCEAppBasics::AppConfigurationBase framework.
#include <UmsciAppConfiguration.h>
Public Types
enum TagID {
CONNECTIONCONFIG ,
VISUCONFIG ,
CONTROLCOLOUR ,
LOOKANDFEEL ,
CONTROLCONFIG ,
CONTROLFORMAT ,
UPMIXCONFIG ,
CONTROLSIZE ,
UPMIXROT ,
UPMIXSCALE ,
UPMIXHEIGHTSCALE ,
UPMIXANGLESTRETCH ,
UPMIXOFFSETX ,
UPMIXOFFSETY
}
Enumerates every XML element tag used in the config file.
enum AttributeID {
ENABLED ,
IP ,
PORT ,
IOSIZE ,
UPMIXSOURCESTARTID ,
UPMIXLIVEMODE ,
UPMIXSHAPE ,
UPMIXSHOWALLSOURCES
}
Enumerates every XML attribute name used within config elements.
Public Member Functions
UmsciAppConfiguration (const File &file)
~UmsciAppConfiguration () override
bool isValid () override
Returns true if the XML file exists and contains the expected root tags.
bool ResetToDefault ()
Overwrites all settings with built-in defaults and triggers a dump.
Static Public Member Functions
static juce::String getTagName (TagID ID)
static juce::String getAttributeName (AttributeID ID)
static bool isValid (const std::unique_ptr< juce::XmlElement > &xmlConfig)
Static overload for validating a pre-loaded XmlElement without an instance.
Protected Member Functions
bool HandleConfigVersionConflict (const Version &configVersionFound) override
Called by the base class when the config file's version string does not match Umsci_CONFIG_VERSION. Currently discards the old file and resets to defaults rather than attempting migration.
Detailed Description
Persists all Umsci user settings to an XML file via the JUCEAppBasics::AppConfigurationBase framework.
XML structure (top-level tags)
Tag (TagID) Contents
CONNECTIONCONFIG IP, port, I/O size (enabled flag, target address).
VISUCONFIG Look-and-feel style, control colour.
CONTROLCOLOUR Packed colour value for source/speaker icons.
LOOKANDFEEL LookAndFeel variant index.
CONTROLCONFIG Control size (S/M/L).
CONTROLFORMAT Upmix channel format (e.g. 5.1, 7.1.4).
UPMIXCONFIG Start source ID, live mode, shape, show-all-sources flag.
CONTROLSIZE Icon size override.
UPMIXROT Upmix ring rotation (float).
UPMIXSCALE Upmix ring radial scale (float).
UPMIXHEIGHTSCALE Upmix height ring scale relative to floor ring (float).
UPMIXANGLESTRETCH Upmix angular stretch factor (float).
UPMIXOFFSETX/Y Upmix ring X/Y centre offset (float each).
MainComponent owns the single instance, registered as both Dumper and Watcher so that settings are written on change and re-applied on external file updates.
Definition at line 54 of file UmsciAppConfiguration.h.
Member Enumeration Documentation
AttributeID
enum UmsciAppConfiguration::AttributeID
Enumerates every XML attribute name used within config elements.
Enumerator
ENABLED
Boolean: whether the connection is active.
IP
String: target device IP address.
PORT
Integer: target OCP.1 port (default 50014).
IOSIZE
String: "inputs,outputs" channel count pair.
UPMIXSOURCESTARTID
Integer: 1-based first DS100 channel for upmix inputs.
UPMIXLIVEMODE
Boolean: follow live DS100 source positions.
UPMIXSHAPE
String: "Circle" or "Rectangle".
UPMIXSHOWALLSOURCES
Boolean: render all sources or only upmix group.
Definition at line 114 of file UmsciAppConfiguration.h.
TagID
enum UmsciAppConfiguration::TagID
Enumerates every XML element tag used in the config file.
Enumerator
CONNECTIONCONFIG
OCP.1 connection parameters.
VISUCONFIG
Visual appearance settings.
CONTROLCOLOUR
Source/speaker icon colour.
LOOKANDFEEL
Look-and-feel variant.
CONTROLCONFIG
Control-component settings.
CONTROLFORMAT
Upmix channel format.
UPMIXCONFIG
Upmix behaviour settings.
CONTROLSIZE
Icon size (S/M/L).
UPMIXROT
Upmix ring rotation.
UPMIXSCALE
Upmix ring radial scale.
UPMIXHEIGHTSCALE
Upmix height ring scale.
UPMIXANGLESTRETCH
Upmix angular stretch.
UPMIXOFFSETX
Upmix X offset.
UPMIXOFFSETY
Upmix Y offset.
Definition at line 59 of file UmsciAppConfiguration.h.
Constructor & Destructor Documentation
UmsciAppConfiguration()
UmsciAppConfiguration::UmsciAppConfiguration (const File & file) explicit
Definition at line 22 of file UmsciAppConfiguration.cpp.
References Umsci_CONFIG_VERSION.
~UmsciAppConfiguration()
UmsciAppConfiguration::~UmsciAppConfiguration () override
Definition at line 28 of file UmsciAppConfiguration.cpp.
Member Function Documentation
getAttributeName()
static juce::String UmsciAppConfiguration::getAttributeName (AttributeID ID) inline static
Definition at line 125 of file UmsciAppConfiguration.h.
References ENABLED, IOSIZE, IP, PORT, UPMIXLIVEMODE, UPMIXSHAPE, UPMIXSHOWALLSOURCES, and UPMIXSOURCESTARTID.
Referenced by UmsciControlComponent::createStateXml(), isValid(), MainComponent::onConfigUpdated(), MainComponent::performConfigurationDump(), and UmsciControlComponent::setStateXml().
getTagName()
static juce::String UmsciAppConfiguration::getTagName (TagID ID) inline static
Definition at line 76 of file UmsciAppConfiguration.h.
References CONNECTIONCONFIG, CONTROLCOLOUR, CONTROLCONFIG, CONTROLFORMAT, CONTROLSIZE, LOOKANDFEEL, UPMIXANGLESTRETCH, UPMIXCONFIG, UPMIXHEIGHTSCALE, UPMIXOFFSETX, UPMIXOFFSETY, UPMIXROT, UPMIXSCALE, and VISUCONFIG.
Referenced by UmsciControlComponent::createStateXml(), isValid(), MainComponent::onConfigUpdated(), MainComponent::performConfigurationDump(), and UmsciControlComponent::setStateXml().
HandleConfigVersionConflict()
bool UmsciAppConfiguration::HandleConfigVersionConflict (const Version & configVersionFound) override protected
Called by the base class when the config file's version string does not match Umsci_CONFIG_VERSION. Currently discards the old file and resets to defaults rather than attempting migration.
Definition at line 149 of file UmsciAppConfiguration.cpp.
References ResetToDefault(), and Umsci_CONFIG_VERSION.
isValid() [1/2]
bool UmsciAppConfiguration::isValid () override
Returns true if the XML file exists and contains the expected root tags.
Definition at line 32 of file UmsciAppConfiguration.cpp.
References isValid().
Referenced by isValid(), and ResetToDefault().
isValid() [2/2]
bool UmsciAppConfiguration::isValid (const std::unique_ptr< juce::XmlElement > & xmlConfig) static
Static overload for validating a pre-loaded XmlElement without an instance.
Definition at line 37 of file UmsciAppConfiguration.cpp.
References CONNECTIONCONFIG, CONTROLCOLOUR, CONTROLCONFIG, getAttributeName(), getTagName(), IOSIZE, IP, LOOKANDFEEL, PORT, UPMIXCONFIG, UPMIXLIVEMODE, UPMIXSHAPE, UPMIXSOURCESTARTID, and VISUCONFIG.
ResetToDefault()
bool UmsciAppConfiguration::ResetToDefault ()
Overwrites all settings with built-in defaults and triggers a dump.
Definition at line 106 of file UmsciAppConfiguration.cpp.
References isValid().
Referenced by HandleConfigVersionConflict().
The documentation for this class was generated from the following files:
Source/UmsciAppConfiguration.h
Source/UmsciAppConfiguration.cpp