Umsci: UmsciExternalControlComponent::OscTab Class Reference
UmsciExternalControlComponent::OscTab Class Reference
Public Member Functions
OscTab (UmsciExternalControlComponent &owner)
void resized () override
void setOscInputPort (int port)
int getOscInputPort () const
void setOscAddr (int param, const juce::String &address)
juce::String getOscAddr (int param) const
Detailed Description
Definition at line 201 of file UmsciExternalControlComponent.cpp.
Constructor & Destructor Documentation
OscTab()
UmsciExternalControlComponent::OscTab::OscTab (UmsciExternalControlComponent & owner) inline
Definition at line 204 of file UmsciExternalControlComponent.cpp.
References UmsciExternalControlComponent::s_oscDefaultAddresses, UmsciExternalControlComponent::s_paramLabels, and UmsciExternalControlComponent::UpmixMidiParam_COUNT.
Member Function Documentation
getOscAddr()
juce::String UmsciExternalControlComponent::OscTab::getOscAddr (int param) const inline
Definition at line 273 of file UmsciExternalControlComponent.cpp.
Referenced by UmsciExternalControlComponent::getOscAddr().
getOscInputPort()
int UmsciExternalControlComponent::OscTab::getOscInputPort () const inline
Definition at line 263 of file UmsciExternalControlComponent.cpp.
Referenced by UmsciExternalControlComponent::getOscInputPort().
resized()
void UmsciExternalControlComponent::OscTab::resized () inline override
Definition at line 234 of file UmsciExternalControlComponent.cpp.
References UmsciExternalControlComponent::UpmixMidiParam_COUNT.
setOscAddr()
void UmsciExternalControlComponent::OscTab::setOscAddr (int param, const juce::String & address) inline
Definition at line 268 of file UmsciExternalControlComponent.cpp.
Referenced by UmsciExternalControlComponent::setOscAddr().
setOscInputPort()
void UmsciExternalControlComponent::OscTab::setOscInputPort (int port) inline
Definition at line 258 of file UmsciExternalControlComponent.cpp.
Referenced by UmsciExternalControlComponent::setOscInputPort().
The documentation for this class was generated from the following file:
Source/UmsciExternalControlComponent.cpp