Umsci: MainApplication::MainWindow Class Reference
MainApplication::MainWindow Class Reference
Public Member Functions
MainWindow (const juce::String &name, const juce::String &commandLine)
void closeButtonPressed () override
void darkModeSettingChanged () override
void applyPaletteStyle (JUCEAppBasics::CustomLookAndFeel::PaletteStyle paletteStyle)
void setFullscreenWindow (bool fullscreenWindow)
Detailed Description
Definition at line 77 of file Main.cpp.
Constructor & Destructor Documentation
MainWindow()
MainApplication::MainWindow::MainWindow (const juce::String & name, const juce::String & commandLine) inline
Definition at line 80 of file Main.cpp.
References applyPaletteStyle(), darkModeSettingChanged(), MainComponent::LookAndFeel_Dark, and setFullscreenWindow().
Member Function Documentation
applyPaletteStyle()
void MainApplication::MainWindow::applyPaletteStyle (JUCEAppBasics::CustomLookAndFeel::PaletteStyle paletteStyle) inline
Definition at line 142 of file Main.cpp.
Referenced by darkModeSettingChanged(), and MainWindow().
closeButtonPressed()
void MainApplication::MainWindow::closeButtonPressed () inline override
Definition at line 118 of file Main.cpp.
darkModeSettingChanged()
void MainApplication::MainWindow::darkModeSettingChanged () inline override
Definition at line 123 of file Main.cpp.
References applyPaletteStyle().
Referenced by MainWindow().
setFullscreenWindow()
void MainApplication::MainWindow::setFullscreenWindow (bool fullscreenWindow) inline
Definition at line 148 of file Main.cpp.
Referenced by MainWindow().
The documentation for this class was generated from the following file:
Source/Main.cpp