Umsci: UmsciControlComponent Class Reference
UmsciControlComponent Class Reference
The main visualisation and interaction surface for Umsci.
#include <UmsciControlComponent.h>
Classes
struct FunctionGroupState
Holds the name and operating mode received from the device for one function group.
Public Member Functions
UmsciControlComponent ()
~UmsciControlComponent () override
void resized () override
void paint (juce::Graphics &g) override
void parentHierarchyChanged () override
std::unique_ptr< XmlElement > createStateXml () override
bool setStateXml (XmlElement *stateXml) override
const std::pair< int, int > & getOcp1IOSize ()
Sets the DS100 input/output channel count for this session.
void setOcp1IOSize (const std::pair< int, int > &ioSize)
void setDeviceName (const std::string &name)
Updates the device name label (shown as a title/overlay in the UI).
void triggerUpmixTransformApplied ()
Fires live-mode position callbacks and onUpmixTransformChanged after a programmatic transform update (e.g. from MIDI control).
void triggerUpmixFlashCheck ()
Starts the flash animation on the upmix indicator if the ideal ring positions diverge from the current DS100 positions.
void setShowAllSources (bool showAll)
When false, only sound objects that are part of the upmix group (i.e. channels >= sourceStartId within the upmix channel count) are rendered; all others are hidden.
bool getShowAllSources () const
void setControlsSize (UmsciPaintNControlComponentBase::ControlsSize size)
Sets the visual size of source/speaker icons (small / medium / large).
UmsciPaintNControlComponentBase::ControlsSize getControlsSize () const
void resetData ()
Clears all cached source/speaker data and marks the database incomplete.
const std::map< std::int16_t, std::string > & getSourceNames () const
Returns the currently cached source names keyed by matrix-input channel number.
const std::map< std::int16_t, std::array< std::float_t, 6 > > & getSpeakerPositions () const
Returns the currently cached speaker positions (X,Y,Z,hor,vrt,rot) keyed by matrix-output number.
const std::map< std::int16_t, FunctionGroupState > & getFunctionGroupData () const
Returns the currently cached function-group state (name + mode) keyed by group ID.
std::vector< std::int16_t > getUpmixSourceIds () const
Returns DS100 source IDs for all currently rendered upmix channels (floor + height).
void setUpmixLevelValue (std::int16_t sourceId, float normalizedLevel)
Delivers a MatrixInput_LevelMeterPostMute value for the given source.
Sound-object (matrix input) setters
Called by setRemoteObject() when the corresponding DS100 notification arrives.
sourceId is 1-based (DS100 channels 1–128).
void setSourceName (std::int16_t sourceId, const std::string &name)
void setSourceMute (std::int16_t sourceId, const std::uint8_t &mute)
0 = unmuted, nonzero = muted.
void setSourceGain (std::int16_t sourceId, const std::float_t &gain)
Gain in dB.
void setSourcePosition (std::int16_t sourceId, const std::array< std::float_t, 3 > &position)
Sets the 3-component (X, Y, Z) absolute position in normalised real-world coordinates.
void setSourceDelayMode (std::int16_t sourceId, const std::uint16_t &delayMode)
Delay mode: 0 = off, 1 = compensate, 2 = reflect (DS100-specific enum).
void setSourceSpread (std::int16_t sourceId, const std::float_t &spread)
Spread factor 0.0–1.0 (0 = point source, 1 = full spread).
Loudspeaker (matrix output) setters
Called by setRemoteObject() when the corresponding DS100 notification arrives.
speakerId is 1-based (DS100 outputs 1–64).
void setSpeakerName (std::int16_t speakerId, const std::string &name)
void setSpeakerMute (std::int16_t speakerId, const std::uint8_t &mute)
void setSpeakerGain (std::int16_t speakerId, const std::float_t &gain)
void setSpeakerPosition (std::int16_t speakerId, const std::array< std::float_t, 6 > &position)
Sets the 6-component speaker position: {X, Y, Z, horizontal angle, vertical angle, rotation}.
void setSpeakerGroup (std::int16_t speakerId, std::int32_t group)
Updates the speaker group assignment for a single output channel.
void setFunctionGroupName (std::int16_t groupId, const std::string &name)
Updates the display name for a single function group.
void setFunctionGroupMode (std::int16_t groupId, std::uint16_t mode)
Updates the mode for a single function group.
Upmix configuration
Settings for the upmix indicator overlay (UmsciUpmixIndicatorPaintNControlComponent).
The upmix indicator shows a ring of virtual speaker positions representing the target upmix channel configuration (e.g. 5.1, 7.1, Atmos). The ring can be rotated, scaled (radius), stretched per-angle, and shifted (offset) by the user via on-screen handles.
sourceStartId identifies the first DS100 sound-object channel that is assigned to the upmix renderer inputs; subsequent channels are implicitly consecutive.
liveMode controls whether the upmix indicator actively follows incoming DS100 position updates or shows a static reference layout.
Note
[MANUAL CONTEXT NEEDED] Describe the upmix workflow: what does the indicator represent, how does it relate to an external upmix renderer, and what the user is expected to do with the transform handles.
void setUpmixChannelConfiguration (const juce::AudioChannelSet &upmixChannelConfig)
const juce::AudioChannelSet getUpmixChannelConfiguration ()
void setUpmixSourceStartId (int startId)
1-based DS100 channel of the first upmix input.
int getUpmixSourceStartId () const
void setUpmixLiveMode (bool liveMode)
true = follow live DS100 positions.
bool getUpmixLiveMode () const
void setUpmixShape (UmsciUpmixIndicatorPaintNControlComponent::IndicatorShape shape)
UmsciUpmixIndicatorPaintNControlComponent::IndicatorShape getUpmixShape () const
void setShowDirectionlessChannel (bool show)
bool getShowDirectionlessChannel () const
void setShowLevelMeter (bool show)
bool getShowLevelMeter () const
Upmix spatial transform
Controls the rotation, radial scale, height translation, and angular stretch of the upmix indicator ring relative to its default position.
All values are in normalised units consistent with the component's coordinate system (see UmsciPaintNControlComponentBase). Changing any of these fires the onUpmixTransformChanged callback so that the values can be persisted.
void setUpmixTransform (float rot, float transH, float transV, float heightTransH, float heightTransV, float angleStretch=1.0f)
float getUpmixRot () const
Ring rotation in normalised units (0–1 → 0–360°).
float getUpmixTransH () const
Floor ring horizontal scale factor.
float getUpmixTransV () const
Floor ring vertical scale factor.
float getUpmixHeightTransH () const
Height ring horizontal scale (fraction of base radius).
float getUpmixHeightTransV () const
Height ring vertical scale (fraction of base radius).
float getUpmixAngleStretch () const
Per-angle stretch factor (1.0 = uniform).
Upmix ring offset
Translates the entire upmix ring in the X/Y plane independently of rotation.
void setUpmixOffset (float x, float y)
float getUpmixOffsetX () const
float getUpmixOffsetY () const
Public Attributes
std::function< void()> onDatabaseComplete
Fired on the message thread when all initially subscribed values have been received from the DS100 (i.e. the "database" is fully populated). Consumers use this to trigger a first full render or to enable UI controls.
std::function< void()> onDeviceDataUpdated
Fired on the message thread whenever a value relevant to dbpr/device synchronisation changes (source name, speaker position, function-group mode).
std::function< void()> onUpmixTransformChanged
Fired on the message thread whenever the user changes any upmix transform parameter via the on-screen handles, so the caller can persist the new values.
std::function< void(std::int16_t, float)> onSourceSpreadReceived
Fired when a Positioning_SourceSpread echo arrives for any subscribed source.
std::function< void(std::int16_t, std::uint16_t)> onSourceDelayModeReceived
Fired when a Positioning_SourceDelayMode echo arrives for any subscribed source.
Detailed Description
The main visualisation and interaction surface for Umsci.
Composition
Three transparent JUCE Components are stacked in z-order, all sharing the same pixel bounds, and all using the same normalised coordinate system managed by UmsciPaintNControlComponentBase:
Layer (z-order) Class Purpose
Bottom UmsciLoudspeakersPaintComponent Paints speaker SVG icons at their real-world positions (read-only).
Middle UmsciSoundobjectsPaintComponent Paints and lets the user drag source circles.
Top UmsciUpmixIndicatorPaintNControlComponent Paints the upmix ring with rotation/scale/stretch handles.
Data flow
DeviceController::onRemoteObjectReceived (message thread) → setRemoteObject().
setRemoteObject() stores the value in m_source* / m_speaker* maps and calls the appropriate setter on the relevant paint component.
The paint component marks itself dirty and repaints on the next message-thread cycle.
"Database complete" concept
On each new connection, UmsciControlComponent waits until initial values have been received for every subscribed object before signalling onDatabaseComplete. Until then the visualisation may show stale or partial data.
Coordinate system
All source and speaker positions received from the DS100 are in a normalised real-world space (roughly 0.0–1.0 for X/Y, see UmsciPaintNControlComponentBase for the exact transform). The paint components convert these to pixel coordinates for rendering.
Note
[MANUAL CONTEXT NEEDED] Document the exact real-world coordinate units used by the DS100 (e.g. metres, normalised 0-1) and how they relate to the stage/room geometry so that contributors understand what the displayed numbers mean physically.
Viewport zoom and sibling synchronisation
All three layers share a single zoom state (scale factor + pan offset). When the user zooms on any layer, that layer fires UmsciPaintNControlComponentBase::onViewportZoomChanged; the syncViewportZoom lambda (wired up in the constructor) forwards the new state to the other two layers via setZoom(), which does not re-fire the callback.
On iOS/iPadOS, JUCE 8's touch routing delivers each finger as a separate MouseEvent routed to whichever component passes hitTest() at that position. Both fingers of a pinch therefore rarely arrive at the same JUCE component, making the JUCE-level processPinchGesture() fallback unreliable. parentHierarchyChanged() therefore attaches a native UIPinchGestureRecognizer (via JUCEAppBasics::iOS_utils::registerNativePinchOnView()) to the JUCE peer UIView the first time a peer becomes available. The UIKit gesture fires at the gesture- recognizer layer before JUCE's per-component touch routing, so it works regardless of which components the individual fingers hit. The incremental scale and centre point are forwarded to simulatePinchZoom() on one of the paint layers, which fires onViewportZoomChanged and thus synchronises all three siblings normally.
Definition at line 92 of file UmsciControlComponent.h.
Constructor & Destructor Documentation
UmsciControlComponent()
UmsciControlComponent::UmsciControlComponent ()
Definition at line 31 of file UmsciControlComponent.cpp.
References onUpmixTransformChanged, DeviceController::RemoteObject::Positioning_SourcePosition, DeviceController::RemObjAddr::sc_INV, and setOcp1IOSize().
~UmsciControlComponent()
UmsciControlComponent::~UmsciControlComponent () override
Definition at line 107 of file UmsciControlComponent.cpp.
Member Function Documentation
createStateXml()
std::unique_ptr< XmlElement > UmsciControlComponent::createStateXml () override
Definition at line 170 of file UmsciControlComponent.cpp.
References UmsciAppConfiguration::CONTROLCONFIG, UmsciAppConfiguration::getAttributeName(), getOcp1IOSize(), UmsciAppConfiguration::getTagName(), and UmsciAppConfiguration::IOSIZE.
getControlsSize()
UmsciPaintNControlComponentBase::ControlsSize UmsciControlComponent::getControlsSize () const
Definition at line 749 of file UmsciControlComponent.cpp.
References UmsciPaintNControlComponentBase::S.
getFunctionGroupData()
const std::map< std::int16_t, FunctionGroupState > & UmsciControlComponent::getFunctionGroupData () const inline
Returns the currently cached function-group state (name + mode) keyed by group ID.
Definition at line 290 of file UmsciControlComponent.h.
getOcp1IOSize()
const std::pair< int, int > & UmsciControlComponent::getOcp1IOSize ()
Sets the DS100 input/output channel count for this session.
The pair is {inputChannels, outputChannels}. It is used to limit which channel IDs are subscribed to and rendered.
The DS100 supports M / L / XL software licenses that set different maximum input and output channel counts. The I/O size is configured by the user in Umsci's connection settings and must match (or be within) the device's licensed capacity — it is not auto-detected from the device.
Note
[MANUAL CONTEXT NEEDED] Confirm whether Umsci validates the configured size against what the device reports, or simply trusts the user entry.
Definition at line 192 of file UmsciControlComponent.cpp.
Referenced by createStateXml(), and setStateXml().
getShowAllSources()
bool UmsciControlComponent::getShowAllSources () const
Definition at line 849 of file UmsciControlComponent.cpp.
getShowDirectionlessChannel()
bool UmsciControlComponent::getShowDirectionlessChannel () const
Definition at line 719 of file UmsciControlComponent.cpp.
getShowLevelMeter()
bool UmsciControlComponent::getShowLevelMeter () const
Definition at line 732 of file UmsciControlComponent.cpp.
getSourceNames()
const std::map< std::int16_t, std::string > & UmsciControlComponent::getSourceNames () const inline
Returns the currently cached source names keyed by matrix-input channel number.
Definition at line 286 of file UmsciControlComponent.h.
getSpeakerPositions()
const std::map< std::int16_t, std::array< std::float_t, 6 > > & UmsciControlComponent::getSpeakerPositions () const inline
Returns the currently cached speaker positions (X,Y,Z,hor,vrt,rot) keyed by matrix-output number.
Definition at line 288 of file UmsciControlComponent.h.
getUpmixAngleStretch()
float UmsciControlComponent::getUpmixAngleStretch () const
Per-angle stretch factor (1.0 = uniform).
Definition at line 797 of file UmsciControlComponent.cpp.
getUpmixChannelConfiguration()
const juce::AudioChannelSet UmsciControlComponent::getUpmixChannelConfiguration ()
Definition at line 664 of file UmsciControlComponent.cpp.
getUpmixHeightTransH()
float UmsciControlComponent::getUpmixHeightTransH () const
Height ring horizontal scale (fraction of base radius).
Definition at line 783 of file UmsciControlComponent.cpp.
getUpmixHeightTransV()
float UmsciControlComponent::getUpmixHeightTransV () const
Height ring vertical scale (fraction of base radius).
Definition at line 790 of file UmsciControlComponent.cpp.
getUpmixLiveMode()
bool UmsciControlComponent::getUpmixLiveMode () const
Definition at line 692 of file UmsciControlComponent.cpp.
getUpmixOffsetX()
float UmsciControlComponent::getUpmixOffsetX () const
Definition at line 822 of file UmsciControlComponent.cpp.
getUpmixOffsetY()
float UmsciControlComponent::getUpmixOffsetY () const
Definition at line 829 of file UmsciControlComponent.cpp.
getUpmixRot()
float UmsciControlComponent::getUpmixRot () const
Ring rotation in normalised units (0–1 → 0–360°).
Definition at line 762 of file UmsciControlComponent.cpp.
getUpmixShape()
UmsciUpmixIndicatorPaintNControlComponent::IndicatorShape UmsciControlComponent::getUpmixShape () const
Definition at line 705 of file UmsciControlComponent.cpp.
References UmsciUpmixIndicatorPaintNControlComponent::Circle.
getUpmixSourceIds()
std::vector< std::int16_t > UmsciControlComponent::getUpmixSourceIds () const
Returns DS100 source IDs for all currently rendered upmix channels (floor + height).
Definition at line 836 of file UmsciControlComponent.cpp.
getUpmixSourceStartId()
int UmsciControlComponent::getUpmixSourceStartId () const
Definition at line 679 of file UmsciControlComponent.cpp.
getUpmixTransH()
float UmsciControlComponent::getUpmixTransH () const
Floor ring horizontal scale factor.
Definition at line 769 of file UmsciControlComponent.cpp.
getUpmixTransV()
float UmsciControlComponent::getUpmixTransV () const
Floor ring vertical scale factor.
Definition at line 776 of file UmsciControlComponent.cpp.
paint()
void UmsciControlComponent::paint (juce::Graphics & g) override
Definition at line 115 of file UmsciControlComponent.cpp.
parentHierarchyChanged()
void UmsciControlComponent::parentHierarchyChanged () override
Definition at line 141 of file UmsciControlComponent.cpp.
resetData()
void UmsciControlComponent::resetData ()
Clears all cached source/speaker data and marks the database incomplete.
Definition at line 531 of file UmsciControlComponent.cpp.
resized()
void UmsciControlComponent::resized () override
Definition at line 127 of file UmsciControlComponent.cpp.
Referenced by setSpeakerPosition().
setControlsSize()
void UmsciControlComponent::setControlsSize (UmsciPaintNControlComponentBase::ControlsSize size)
Sets the visual size of source/speaker icons (small / medium / large).
Definition at line 739 of file UmsciControlComponent.cpp.
setDeviceName()
void UmsciControlComponent::setDeviceName (const std::string & name)
Updates the device name label (shown as a title/overlay in the UI).
Definition at line 536 of file UmsciControlComponent.cpp.
setFunctionGroupMode()
void UmsciControlComponent::setFunctionGroupMode (std::int16_t groupId, std::uint16_t mode)
Updates the mode for a single function group.
Definition at line 650 of file UmsciControlComponent.cpp.
References onDeviceDataUpdated.
setFunctionGroupName()
void UmsciControlComponent::setFunctionGroupName (std::int16_t groupId, const std::string & name)
Updates the display name for a single function group.
Definition at line 643 of file UmsciControlComponent.cpp.
References onDeviceDataUpdated.
setOcp1IOSize()
void UmsciControlComponent::setOcp1IOSize (const std::pair< int, int > & ioSize)
Definition at line 197 of file UmsciControlComponent.cpp.
Referenced by setStateXml(), and UmsciControlComponent().
setShowAllSources()
void UmsciControlComponent::setShowAllSources (bool showAll)
When false, only sound objects that are part of the upmix group (i.e. channels >= sourceStartId within the upmix channel count) are rendered; all others are hidden.
Definition at line 843 of file UmsciControlComponent.cpp.
setShowDirectionlessChannel()
void UmsciControlComponent::setShowDirectionlessChannel (bool show)
Definition at line 712 of file UmsciControlComponent.cpp.
setShowLevelMeter()
void UmsciControlComponent::setShowLevelMeter (bool show)
Definition at line 726 of file UmsciControlComponent.cpp.
setSourceDelayMode()
void UmsciControlComponent::setSourceDelayMode (std::int16_t sourceId, const std::uint16_t & delayMode)
Delay mode: 0 = off, 1 = compensate, 2 = reflect (DS100-specific enum).
Definition at line 578 of file UmsciControlComponent.cpp.
References onSourceDelayModeReceived.
setSourceGain()
void UmsciControlComponent::setSourceGain (std::int16_t sourceId, const std::float_t & gain)
Gain in dB.
Definition at line 562 of file UmsciControlComponent.cpp.
setSourceMute()
void UmsciControlComponent::setSourceMute (std::int16_t sourceId, const std::uint8_t & mute)
0 = unmuted, nonzero = muted.
Definition at line 547 of file UmsciControlComponent.cpp.
setSourceName()
void UmsciControlComponent::setSourceName (std::int16_t sourceId, const std::string & name)
Definition at line 541 of file UmsciControlComponent.cpp.
References onDeviceDataUpdated.
setSourcePosition()
void UmsciControlComponent::setSourcePosition (std::int16_t sourceId, const std::array< std::float_t, 3 > & position)
Sets the 3-component (X, Y, Z) absolute position in normalised real-world coordinates.
Definition at line 567 of file UmsciControlComponent.cpp.
setSourceSpread()
void UmsciControlComponent::setSourceSpread (std::int16_t sourceId, const std::float_t & spread)
Spread factor 0.0–1.0 (0 = point source, 1 = full spread).
Definition at line 584 of file UmsciControlComponent.cpp.
References onSourceSpreadReceived.
setSpeakerGain()
void UmsciControlComponent::setSpeakerGain (std::int16_t speakerId, const std::float_t & gain)
Definition at line 609 of file UmsciControlComponent.cpp.
setSpeakerGroup()
void UmsciControlComponent::setSpeakerGroup (std::int16_t speakerId, std::int32_t group)
Updates the speaker group assignment for a single output channel.
Definition at line 638 of file UmsciControlComponent.cpp.
setSpeakerMute()
void UmsciControlComponent::setSpeakerMute (std::int16_t speakerId, const std::uint8_t & mute)
Definition at line 595 of file UmsciControlComponent.cpp.
setSpeakerName()
void UmsciControlComponent::setSpeakerName (std::int16_t speakerId, const std::string & name)
Definition at line 590 of file UmsciControlComponent.cpp.
setSpeakerPosition()
void UmsciControlComponent::setSpeakerPosition (std::int16_t speakerId, const std::array< std::float_t, 6 > & position)
Sets the 6-component speaker position: {X, Y, Z, horizontal angle, vertical angle, rotation}.
Note
[MANUAL CONTEXT NEEDED] Document the exact units and axis conventions for each of the 6 components (e.g. metres vs. normalised, degrees vs. radians, coordinate handedness).
Definition at line 614 of file UmsciControlComponent.cpp.
References onDeviceDataUpdated, and resized().
setStateXml()
bool UmsciControlComponent::setStateXml (XmlElement * stateXml) override
Definition at line 179 of file UmsciControlComponent.cpp.
References UmsciAppConfiguration::CONTROLCONFIG, UmsciAppConfiguration::getAttributeName(), getOcp1IOSize(), UmsciAppConfiguration::getTagName(), UmsciAppConfiguration::IOSIZE, and setOcp1IOSize().
setUpmixChannelConfiguration()
void UmsciControlComponent::setUpmixChannelConfiguration (const juce::AudioChannelSet & upmixChannelConfig)
Definition at line 657 of file UmsciControlComponent.cpp.
setUpmixLevelValue()
void UmsciControlComponent::setUpmixLevelValue (std::int16_t sourceId, float normalizedLevel)
Delivers a MatrixInput_LevelMeterPostMute value for the given source.
Called from setRemoteObject() when the corresponding OCP.1 notification arrives. Forwards to the level meter overlay if the channel belongs to the current upmix group.
Parameters
sourceId 1-based DS100 matrix-input channel.
normalizedLevel Linear level factor [0, 1].
Definition at line 871 of file UmsciControlComponent.cpp.
setUpmixLiveMode()
void UmsciControlComponent::setUpmixLiveMode (bool liveMode)
true = follow live DS100 positions.
Definition at line 686 of file UmsciControlComponent.cpp.
setUpmixOffset()
void UmsciControlComponent::setUpmixOffset (float x, float y)
Definition at line 804 of file UmsciControlComponent.cpp.
setUpmixShape()
void UmsciControlComponent::setUpmixShape (UmsciUpmixIndicatorPaintNControlComponent::IndicatorShape shape)
Definition at line 699 of file UmsciControlComponent.cpp.
setUpmixSourceStartId()
void UmsciControlComponent::setUpmixSourceStartId (int startId)
1-based DS100 channel of the first upmix input.
Definition at line 672 of file UmsciControlComponent.cpp.
setUpmixTransform()
void UmsciControlComponent::setUpmixTransform (float rot, float transH, float transV, float heightTransH, float heightTransV, float angleStretch = 1.0f)
Definition at line 756 of file UmsciControlComponent.cpp.
triggerUpmixFlashCheck()
void UmsciControlComponent::triggerUpmixFlashCheck ()
Starts the flash animation on the upmix indicator if the ideal ring positions diverge from the current DS100 positions.
Call this after a programmatic transform update when live mode is off, so the operator sees a visual cue that the device positions are out of sync.
Definition at line 816 of file UmsciControlComponent.cpp.
triggerUpmixTransformApplied()
void UmsciControlComponent::triggerUpmixTransformApplied ()
Fires live-mode position callbacks and onUpmixTransformChanged after a programmatic transform update (e.g. from MIDI control).
Call this after setUpmixTransform() / setUpmixOffset() when the change originates outside the UI (MIDI, automation) to ensure DS100 positions are updated in live mode and the config is marked dirty.
Definition at line 810 of file UmsciControlComponent.cpp.
Member Data Documentation
onDatabaseComplete
std::function<void()> UmsciControlComponent::onDatabaseComplete
Fired on the message thread when all initially subscribed values have been received from the DS100 (i.e. the "database" is fully populated). Consumers use this to trigger a first full render or to enable UI controls.
Definition at line 298 of file UmsciControlComponent.h.
onDeviceDataUpdated
std::function<void()> UmsciControlComponent::onDeviceDataUpdated
Fired on the message thread whenever a value relevant to dbpr/device synchronisation changes (source name, speaker position, function-group mode).
Definition at line 304 of file UmsciControlComponent.h.
Referenced by setFunctionGroupMode(), setFunctionGroupName(), setSourceName(), and setSpeakerPosition().
onSourceDelayModeReceived
std::function<void(std::int16_t, std::uint16_t)> UmsciControlComponent::onSourceDelayModeReceived
Fired when a Positioning_SourceDelayMode echo arrives for any subscribed source.
Definition at line 318 of file UmsciControlComponent.h.
Referenced by setSourceDelayMode().
onSourceSpreadReceived
std::function<void(std::int16_t, float)> UmsciControlComponent::onSourceSpreadReceived
Fired when a Positioning_SourceSpread echo arrives for any subscribed source.
Definition at line 316 of file UmsciControlComponent.h.
Referenced by setSourceSpread().
onUpmixTransformChanged
std::function<void()> UmsciControlComponent::onUpmixTransformChanged
Fired on the message thread whenever the user changes any upmix transform parameter via the on-screen handles, so the caller can persist the new values.
Definition at line 310 of file UmsciControlComponent.h.
Referenced by UmsciControlComponent().
The documentation for this class was generated from the following files:
Source/UmsciControlComponent.h
Source/UmsciControlComponent.cpp