Umsci: UmsciExternalControlComponent::MidiTab Class Reference
UmsciExternalControlComponent::MidiTab Class Reference
Public Member Functions
MidiTab (UmsciExternalControlComponent &owner)
void resized () override
void comboBoxChanged (juce::ComboBox *cb) override
void setMidiInputDeviceIdentifier (const juce::String &identifier)
const juce::String & getMidiInputDeviceIdentifier () const
void setMidiAssi (int param, const JUCEAppBasics::MidiCommandRangeAssignment &assi)
const JUCEAppBasics::MidiCommandRangeAssignment & getMidiAssi (int param) const
Detailed Description
Definition at line 55 of file UmsciExternalControlComponent.cpp.
Constructor & Destructor Documentation
MidiTab()
UmsciExternalControlComponent::MidiTab::MidiTab (UmsciExternalControlComponent & owner) inline
Definition at line 59 of file UmsciExternalControlComponent.cpp.
References UmsciExternalControlComponent::onMidiAssiChanged, UmsciExternalControlComponent::s_paramLabels, and UmsciExternalControlComponent::UpmixMidiParam_COUNT.
Member Function Documentation
comboBoxChanged()
void UmsciExternalControlComponent::MidiTab::comboBoxChanged (juce::ComboBox * cb) inline override
Definition at line 115 of file UmsciExternalControlComponent.cpp.
References UmsciExternalControlComponent::onMidiInputDeviceChanged, and UmsciExternalControlComponent::UpmixMidiParam_COUNT.
getMidiAssi()
const JUCEAppBasics::MidiCommandRangeAssignment & UmsciExternalControlComponent::MidiTab::getMidiAssi (int param) const inline
Definition at line 160 of file UmsciExternalControlComponent.cpp.
Referenced by UmsciExternalControlComponent::getMidiAssi().
getMidiInputDeviceIdentifier()
const juce::String & UmsciExternalControlComponent::MidiTab::getMidiInputDeviceIdentifier () const inline
Definition at line 150 of file UmsciExternalControlComponent.cpp.
Referenced by UmsciExternalControlComponent::getMidiInputDeviceIdentifier().
resized()
void UmsciExternalControlComponent::MidiTab::resized () inline override
Definition at line 91 of file UmsciExternalControlComponent.cpp.
References UmsciExternalControlComponent::UpmixMidiParam_COUNT.
setMidiAssi()
void UmsciExternalControlComponent::MidiTab::setMidiAssi (int param, const JUCEAppBasics::MidiCommandRangeAssignment & assi) inline
Definition at line 155 of file UmsciExternalControlComponent.cpp.
Referenced by UmsciExternalControlComponent::setMidiAssi().
setMidiInputDeviceIdentifier()
void UmsciExternalControlComponent::MidiTab::setMidiInputDeviceIdentifier (const juce::String & identifier) inline
Definition at line 133 of file UmsciExternalControlComponent.cpp.
References UmsciExternalControlComponent::UpmixMidiParam_COUNT.
Referenced by UmsciExternalControlComponent::setMidiInputDeviceIdentifier().
The documentation for this class was generated from the following file:
Source/UmsciExternalControlComponent.cpp