var dir_74389ed8173ad57b461b9d623a1f3867 =
[
    [ "UmsciPaintNControlComponents", "dir_0922d4c3162f89e605943002003a4fc1.html", "dir_0922d4c3162f89e605943002003a4fc1" ],
    [ "AboutComponent.cpp", "AboutComponent_8cpp.html", null ],
    [ "AboutComponent.h", "AboutComponent_8h.html", "AboutComponent_8h" ],
    [ "CustomPopupMenuComponent.h", "CustomPopupMenuComponent_8h.html", "CustomPopupMenuComponent_8h" ],
    [ "DbprController.cpp", "DbprController_8cpp.html", null ],
    [ "DbprController.h", "DbprController_8h.html", "DbprController_8h" ],
    [ "dbprProjectUtils.cpp", "dbprProjectUtils_8cpp.html", null ],
    [ "dbprProjectUtils.h", "dbprProjectUtils_8h.html", null ],
    [ "DeviceController.cpp", "DeviceController_8cpp.html", null ],
    [ "DeviceController.h", "DeviceController_8h.html", "DeviceController_8h" ],
    [ "Main.cpp", "Main_8cpp.html", "Main_8cpp" ],
    [ "MainComponent.cpp", "MainComponent_8cpp.html", null ],
    [ "MainComponent.h", "MainComponent_8h.html", "MainComponent_8h" ],
    [ "MidiController.cpp", "MidiController_8cpp.html", null ],
    [ "MidiController.h", "MidiController_8h.html", "MidiController_8h" ],
    [ "OscController.cpp", "OscController_8cpp.html", null ],
    [ "OscController.h", "OscController_8h.html", "OscController_8h" ],
    [ "UmsciAppConfiguration.cpp", "UmsciAppConfiguration_8cpp.html", null ],
    [ "UmsciAppConfiguration.h", "UmsciAppConfiguration_8h.html", "UmsciAppConfiguration_8h" ],
    [ "UmsciConnectingComponent.cpp", "UmsciConnectingComponent_8cpp.html", null ],
    [ "UmsciConnectingComponent.h", "UmsciConnectingComponent_8h.html", "UmsciConnectingComponent_8h" ],
    [ "UmsciControlComponent.cpp", "UmsciControlComponent_8cpp.html", null ],
    [ "UmsciControlComponent.h", "UmsciControlComponent_8h.html", "UmsciControlComponent_8h" ],
    [ "UmsciDiscoveringHintComponent.cpp", "UmsciDiscoveringHintComponent_8cpp.html", null ],
    [ "UmsciDiscoveringHintComponent.h", "UmsciDiscoveringHintComponent_8h.html", "UmsciDiscoveringHintComponent_8h" ],
    [ "UmsciExternalControlComponent.cpp", "UmsciExternalControlComponent_8cpp.html", "UmsciExternalControlComponent_8cpp" ],
    [ "UmsciExternalControlComponent.h", "UmsciExternalControlComponent_8h.html", "UmsciExternalControlComponent_8h" ],
    [ "UmsciZeroconfDiscoverComboComponent.cpp", "UmsciZeroconfDiscoverComboComponent_8cpp.html", null ],
    [ "UmsciZeroconfDiscoverComboComponent.h", "UmsciZeroconfDiscoverComboComponent_8h.html", "UmsciZeroconfDiscoverComboComponent_8h" ]
];