var searchData=
[
  ['a_20new_20subscribed_20object_0',['How to add a new subscribed object',['../classDeviceController.html#autotoc_md4',1,'']]],
  ['aboutcomponent_1',['aboutcomponent',['../classAboutComponent.html#aba5dd2f2dab50c420b74b80a0cb9ef34',1,'AboutComponent::AboutComponent()'],['../classAboutComponent.html',1,'AboutComponent']]],
  ['aboutcomponent_2ecpp_2',['AboutComponent.cpp',['../AboutComponent_8cpp.html',1,'']]],
  ['aboutcomponent_2eh_3',['AboutComponent.h',['../AboutComponent_8h.html',1,'']]],
  ['adaptation_20inside_20alertwindow_4',['Layout adaptation inside AlertWindow',['../classUmsciZeroconfDiscoverComboComponent.html#autotoc_md34',1,'']]],
  ['add_20a_20new_20subscribed_20object_5',['How to add a new subscribed object',['../classDeviceController.html#autotoc_md4',1,'']]],
  ['added_6',['added',['../md_CHANGELOG.html#autotoc_md103',1,'Added'],['../md_CHANGELOG.html#autotoc_md99',1,'Added'],['../md_CHANGELOG.html#autotoc_md95',1,'Added'],['../md_CHANGELOG.html#autotoc_md91',1,'Added'],['../md_CHANGELOG.html#autotoc_md87',1,'Added'],['../md_CHANGELOG.html#autotoc_md83',1,'Added'],['../md_CHANGELOG.html#autotoc_md79',1,'Added']]],
  ['addr_7',['Addr',['../structDeviceController_1_1RemoteObject.html#a60a06af8d487a542104c6e81e629c01b',1,'DeviceController::RemoteObject']]],
  ['addressing_8',['Addressing',['../classDeviceController.html#autotoc_md2',1,'']]],
  ['adjust_20the_20upmix_20indicator_9',['Step 4 — Set up and adjust the upmix indicator',['../index.html#autotoc_md45',1,'']]],
  ['alertwindow_10',['Layout adaptation inside AlertWindow',['../classUmsciZeroconfDiscoverComboComponent.html#autotoc_md34',1,'']]],
  ['align_20the_20ring_20to_20the_20room_11',['4b — Align the ring to the room',['../index.html#autotoc_md47',1,'']]],
  ['alignment_12',['Upmix monitoring and alignment',['../index.html#autotoc_md51',1,'']]],
  ['and_20adjust_20the_20upmix_20indicator_13',['Step 4 — Set up and adjust the upmix indicator',['../index.html#autotoc_md45',1,'']]],
  ['and_20alignment_14',['Upmix monitoring and alignment',['../index.html#autotoc_md51',1,'']]],
  ['and_20editing_15',['General soundobject position monitoring and editing',['../index.html#autotoc_md52',1,'']]],
  ['and_20embedded_20deployment_16',['Kiosk and embedded deployment',['../index.html#autotoc_md68',1,'']]],
  ['and_20first_20soundobject_17',['4a — Choose the channel format and first soundobject',['../index.html#autotoc_md46',1,'']]],
  ['and_20hittest_20dead_20zones_18',['Touch-zoom and hitTest dead zones',['../classUmsciSoundobjectsPaintComponent.html#autotoc_md26',1,'']]],
  ['and_20pan_19',['Zoom and pan',['../index.html#autotoc_md59',1,'']]],
  ['and_20pan_20internals_20',['Zoom and pan internals',['../index.html#autotoc_md73',1,'']]],
  ['and_20sibling_20synchronisation_21',['Viewport zoom and sibling synchronisation',['../classUmsciControlComponent.html#autotoc_md16',1,'']]],
  ['and_20touch_20routing_22',['hitTest and touch routing',['../classUmsciUpmixIndicatorPaintNControlComponent.html#autotoc_md31',1,'']]],
  ['and_20verify_23',['Step 2 — Connect and verify',['../index.html#autotoc_md41',1,'']]],
  ['anotherinstancestarted_24',['anotherInstanceStarted',['../classMainApplication.html#abf43e959a633ba02a2bae4d9f058a900',1,'MainApplication']]],
  ['app_20functionality_25',['Umsci - app functionality',['../index.html#autotoc_md56',1,'']]],
  ['application_20architecture_20overview_26',['Application architecture overview',['../classMainComponent.html#autotoc_md6',1,'']]],
  ['applypalettestyle_27',['applyPaletteStyle',['../classMainApplication_1_1MainWindow.html#ab9716a08bda1af74eea932259dbf5b60',1,'MainApplication::MainWindow']]],
  ['applysettingsoption_28',['applySettingsOption',['../classMainComponent.html#a453a0ee11db0ab1baae366e976d79647',1,'MainComponent']]],
  ['architecture_29',['Code architecture',['../index.html#autotoc_md70',1,'']]],
  ['architecture_20overview_30',['Application architecture overview',['../classMainComponent.html#autotoc_md6',1,'']]],
  ['assignments_31',['Parameter assignments',['../index.html#autotoc_md66',1,'']]],
  ['attributeid_32',['AttributeID',['../classUmsciAppConfiguration.html#a5e67616c3aac0b239721e86c4837ad61',1,'UmsciAppConfiguration']]]
];
