var searchData=
[
  ['a_20new_20subscribed_20object_0',['How to add a new subscribed object',['../classDeviceController.html#autotoc_md4',1,'']]],
  ['aboutcomponent_1',['aboutcomponent',['../classAboutComponent.html#aba5dd2f2dab50c420b74b80a0cb9ef34',1,'AboutComponent::AboutComponent()'],['../classAboutComponent.html',1,'AboutComponent']]],
  ['aboutcomponent_2ecpp_2',['AboutComponent.cpp',['../AboutComponent_8cpp.html',1,'']]],
  ['aboutcomponent_2eh_3',['AboutComponent.h',['../AboutComponent_8h.html',1,'']]],
  ['adaptation_20inside_20alertwindow_4',['Layout adaptation inside AlertWindow',['../classUmsciZeroconfDiscoverComboComponent.html#autotoc_md38',1,'']]],
  ['add_20a_20new_20subscribed_20object_5',['How to add a new subscribed object',['../classDeviceController.html#autotoc_md4',1,'']]],
  ['added_6',['added',['../md_CHANGELOG.html#autotoc_md116',1,'Added'],['../md_CHANGELOG.html#autotoc_md112',1,'Added'],['../md_CHANGELOG.html#autotoc_md108',1,'Added'],['../md_CHANGELOG.html#autotoc_md104',1,'Added'],['../md_CHANGELOG.html#autotoc_md100',1,'Added'],['../md_CHANGELOG.html#autotoc_md96',1,'Added'],['../md_CHANGELOG.html#autotoc_md92',1,'Added'],['../md_CHANGELOG.html#autotoc_md88',1,'Added']]],
  ['addr_7',['Addr',['../structDeviceController_1_1RemoteObject.html#a60a06af8d487a542104c6e81e629c01b',1,'DeviceController::RemoteObject']]],
  ['addressing_8',['Addressing',['../classDeviceController.html#autotoc_md2',1,'']]],
  ['adjust_20the_20upmix_20indicator_9',['Step 4 — Set up and adjust the upmix indicator',['../index.html#autotoc_md49',1,'']]],
  ['alertwindow_10',['Layout adaptation inside AlertWindow',['../classUmsciZeroconfDiscoverComboComponent.html#autotoc_md38',1,'']]],
  ['align_20the_20ring_20to_20the_20room_11',['4b — Align the ring to the room',['../index.html#autotoc_md51',1,'']]],
  ['alignment_12',['Upmix monitoring and alignment',['../index.html#autotoc_md55',1,'']]],
  ['and_20adjust_20the_20upmix_20indicator_13',['Step 4 — Set up and adjust the upmix indicator',['../index.html#autotoc_md49',1,'']]],
  ['and_20alignment_14',['Upmix monitoring and alignment',['../index.html#autotoc_md55',1,'']]],
  ['and_20editing_15',['General soundobject position monitoring and editing',['../index.html#autotoc_md56',1,'']]],
  ['and_20embedded_20deployment_16',['Kiosk and embedded deployment',['../index.html#autotoc_md76',1,'']]],
  ['and_20first_20soundobject_17',['4a — Choose the channel format and first soundobject',['../index.html#autotoc_md50',1,'']]],
  ['and_20hittest_20dead_20zones_18',['Touch-zoom and hitTest dead zones',['../classUmsciSoundobjectsPaintComponent.html#autotoc_md30',1,'']]],
  ['and_20pan_19',['Zoom and pan',['../index.html#autotoc_md63',1,'']]],
  ['and_20pan_20internals_20',['Zoom and pan internals',['../index.html#autotoc_md81',1,'']]],
  ['and_20sibling_20synchronisation_21',['Viewport zoom and sibling synchronisation',['../classUmsciControlComponent.html#autotoc_md16',1,'']]],
  ['and_20touch_20routing_22',['hitTest and touch routing',['../classUmsciUpmixIndicatorPaintNControlComponent.html#autotoc_md35',1,'']]],
  ['and_20verify_23',['Step 2 — Connect and verify',['../index.html#autotoc_md45',1,'']]],
  ['anglestretch_24',['angleStretch',['../structUmsciSnapshotComponent_1_1UpmixSnapshot.html#a5073f91329d37e33ca24ceba7ce227cb',1,'UmsciSnapshotComponent::UpmixSnapshot']]],
  ['anotherinstancestarted_25',['anotherInstanceStarted',['../classMainApplication.html#abf43e959a633ba02a2bae4d9f058a900',1,'MainApplication']]],
  ['app_20functionality_26',['Umsci - app functionality',['../index.html#autotoc_md60',1,'']]],
  ['application_20architecture_20overview_27',['Application architecture overview',['../classMainComponent.html#autotoc_md6',1,'']]],
  ['applypalettestyle_28',['applyPaletteStyle',['../classMainApplication_1_1MainWindow.html#ab9716a08bda1af74eea932259dbf5b60',1,'MainApplication::MainWindow']]],
  ['applysettingsoption_29',['applySettingsOption',['../classMainComponent.html#a453a0ee11db0ab1baae366e976d79647',1,'MainComponent']]],
  ['architecture_30',['Code architecture',['../index.html#autotoc_md78',1,'']]],
  ['architecture_20overview_31',['Application architecture overview',['../classMainComponent.html#autotoc_md6',1,'']]],
  ['assignments_32',['Parameter assignments',['../index.html#autotoc_md74',1,'']]],
  ['attributeid_33',['AttributeID',['../classUmsciAppConfiguration.html#a5e67616c3aac0b239721e86c4837ad61',1,'UmsciAppConfiguration']]]
];
